module.exports = {
    ADD_TODO:"ADD_TODO",
    DELETE_TODO:"DELETE_TODO",
    CHANGE_STATE_TODO:"CHANGE_STATE_TODO",
    CLICK_INCREMENT_COUNDER:"CLICK_INCREMENT_COUNDER",
    HOVER_INCREMENT_COUNDER:"HOVER_INCREMENT_COUNDER",
    CLICK_DECREMENT_COUNDER:"CLICK_DECREMENT_COUNDER",
    HOVER_DECREMENT_COUNDER:"HOVER_DECREMENT_COUNDER",
    FETCH_SUCCESS:"FETCH_SUCCESS",
    FETCH_FAILURE:"FETCH_FAILURE",
    USERS_DATA:"USERS_DATA"
}